name: "checks"
on: push
jobs:
  main:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version-file: '.python-version'

      - name: Setup Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: make install-deps

      - name: Check Smells
        run: make check-all

      - name: Unit Tests
        run: make test
